### ISSUE TITLE
Language server crashes when no default model is defined in the manifest

### ISSUE THREAD

**Issue by HappyHepo** [SAP/ui5-language-assistant#552]
When having a UI5 project without the default unnamed model being defined in the manifest, the Language server crashes on opening an XML view.
Minimal reproduction: [webapp.zip](https://github.com/SAP/ui5-language-assistant/files/10566292/webapp.zip)
[log.txt](https://github.com/SAP/ui5-language-assistant/files/10566314/log.txt)

This seems to be coming from here: https://github.com/SAP/ui5-language-assistant/blob/master/packages/context/src/manifest.ts#L101

**Comment by sojimaxi** [comment]
I am experiencing the same issue and not able to use the extension

**Comment by mofterdinger** [comment]
Hi, I'm getting exactly the same issue when I try to open a view xml file:
```
/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110739
    return (_d = (_c = manifest["sap.ui5"]) === null || _c === void 0 ? void 0 : _c.models) === null || _d === void 0 ? void 0 : _d[model].dataSource;
                                                                                                                                           ^

TypeError: Cannot read properties of undefined (reading 'dataSource')
    at getMainService (/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110739:140)
    at extractManifestDetails (/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110800:35)
    at Object.getManifestDetails (/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110834:12)
    at async Object.getContext (/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110228:29)
    at async /Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:127467:25
[Info  - 10:23:44] Connection to server got closed. Server will restart.
[Error - 10:23:44] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'dataSource')
  Code: -32603 
[Error - 10:23:45] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'dataSource')
  Code: -32603 
[Error - 10:23:45] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'dataSource')
  Code: -32603 
/Users/d032842/.vscode/extensions/saposs.vscode-ui5-language-assistant-4.0.3/node_modules/@ui5-language-assistant/language-server/dist/server.js:110739
    return (_d = (_c = manifest["sap.ui5"]) === null || _c === void 0 ? void 0 : _c.models) === null || _d === void 0 ? void 0 : _d[model].dataSource;
                                                                                                                                         ^
```

Is there any workaround available until it gets fixed? Currently I can't use this extension.

**Comment by mofterdinger** [comment]
As workaround I found this solution in the manifest.json:
```
    "models": {
      "": {
        "type": "sap.ui.model.json.JSONModel"
      }
    },
```
Just added the model "".

**Comment by MN-public** [comment]
@HappyHepo 
We just released a version with fixes to this issue. Could you please check if it works for you now? Thanks

**Comment by HappyHepo** [comment]
Works again, thanks!
